name: CI

on:
  workflow_dispatch:

permissions:
  id-token: write     # nécessaire pour OIDC
  contents: read      # nécessaire pour checkout

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::069987675187:role/ngasmi
          aws-region: eu-west-1

      - name: List buckets to test OIDC connection
        run: |
          aws s3 ls
